'''
Decoder model is used to decode the tokens generated by the Fourier coefficients model back to the encoded image encoded by the vae model.
The encoded  can be sampled to reconstruct the original image using the vae model decoder.
'''
import torch
import torch.nn as nn
import torch.nn.functional as F
from timm.models.vision_transformer import PatchEmbed, Attention
import numpy as np

